# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consolewindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsoleWindow(object):
    def setupUi(self, ConsoleWindow):
        ConsoleWindow.setObjectName("ConsoleWindow")
        ConsoleWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ConsoleWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.consoleTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.consoleTextEdit.setFont(font)
        self.consoleTextEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.consoleTextEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.consoleTextEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.consoleTextEdit.setObjectName("consoleTextEdit")
        self.verticalLayout.addWidget(self.consoleTextEdit)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmdLineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.cmdLineEdit.setFont(font)
        self.cmdLineEdit.setObjectName("cmdLineEdit")
        self.horizontalLayout.addWidget(self.cmdLineEdit)
        self.sendButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.verticalLayout.addWidget(self.frame)
        ConsoleWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ConsoleWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        ConsoleWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ConsoleWindow)
        self.statusbar.setObjectName("statusbar")
        ConsoleWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(ConsoleWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ConsoleWindow)
        QtCore.QMetaObject.connectSlotsByName(ConsoleWindow)

    def retranslateUi(self, ConsoleWindow):
        _translate = QtCore.QCoreApplication.translate
        ConsoleWindow.setWindowTitle(_translate("ConsoleWindow", "MainWindow"))
        self.sendButton.setText(_translate("ConsoleWindow", "Send"))
        self.menuFile.setTitle(_translate("ConsoleWindow", "File"))
        self.actionClose.setText(_translate("ConsoleWindow", "Close Window"))
        self.actionClose.setShortcut(_translate("ConsoleWindow", "Ctrl+W"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConsoleWindow = QtWidgets.QMainWindow()
    ui = Ui_ConsoleWindow()
    ui.setupUi(ConsoleWindow)
    ConsoleWindow.show()
    sys.exit(app.exec_())
