# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 800)
        MainWindow.setMinimumSize(QtCore.QSize(480, 800))
        MainWindow.setMaximumSize(QtCore.QSize(480, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../../../Desktop/unnamed.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.commsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.commsBox.setGeometry(QtCore.QRect(10, 0, 461, 61))
        self.commsBox.setObjectName("commsBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.commsBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refreshButton = QtWidgets.QPushButton(self.commsBox)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)
        self.comPortComboBox = QtWidgets.QComboBox(self.commsBox)
        self.comPortComboBox.setObjectName("comPortComboBox")
        self.comPortComboBox.addItem("")
        self.horizontalLayout.addWidget(self.comPortComboBox)
        self.connectButton = QtWidgets.QPushButton(self.commsBox)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        self.setUpBox = QtWidgets.QGroupBox(self.centralwidget)
        self.setUpBox.setGeometry(QtCore.QRect(10, 70, 461, 56))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setUpBox.sizePolicy().hasHeightForWidth())
        self.setUpBox.setSizePolicy(sizePolicy)
        self.setUpBox.setObjectName("setUpBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.setUpBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.syringeComboBox = QtWidgets.QComboBox(self.setUpBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syringeComboBox.sizePolicy().hasHeightForWidth())
        self.syringeComboBox.setSizePolicy(sizePolicy)
        self.syringeComboBox.setObjectName("syringeComboBox")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.syringeComboBox)
        self.syringeButton = QtWidgets.QPushButton(self.setUpBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syringeButton.sizePolicy().hasHeightForWidth())
        self.syringeButton.setSizePolicy(sizePolicy)
        self.syringeButton.setObjectName("syringeButton")
        self.horizontalLayout_2.addWidget(self.syringeButton)
        self.initializeButton = QtWidgets.QPushButton(self.setUpBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initializeButton.sizePolicy().hasHeightForWidth())
        self.initializeButton.setSizePolicy(sizePolicy)
        self.initializeButton.setObjectName("initializeButton")
        self.horizontalLayout_2.addWidget(self.initializeButton)
        self.emergencyStopBox = QtWidgets.QGroupBox(self.centralwidget)
        self.emergencyStopBox.setGeometry(QtCore.QRect(10, 690, 461, 56))
        self.emergencyStopBox.setObjectName("emergencyStopBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.emergencyStopBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stopButton = QtWidgets.QPushButton(self.emergencyStopBox)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout_6.addWidget(self.stopButton)
        self.dispenseBox = QtWidgets.QGroupBox(self.centralwidget)
        self.dispenseBox.setGeometry(QtCore.QRect(10, 330, 461, 361))
        self.dispenseBox.setObjectName("dispenseBox")
        self.columnSelectBox = QtWidgets.QGroupBox(self.dispenseBox)
        self.columnSelectBox.setGeometry(QtCore.QRect(10, 90, 441, 261))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.columnSelectBox.setFont(font)
        self.columnSelectBox.setObjectName("columnSelectBox")
        self.layoutWidget = QtWidgets.QWidget(self.columnSelectBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 421, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.allCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.allCheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.allCheckBox.setFont(font)
        self.allCheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.allCheckBox.setObjectName("allCheckBox")
        self.horizontalLayout_3.addWidget(self.allCheckBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.column1CheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.column1CheckBox.setFont(font)
        self.column1CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column1CheckBox.setObjectName("column1CheckBox")
        self.verticalLayout_3.addWidget(self.column1CheckBox)
        self.column2CheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.column2CheckBox.setFont(font)
        self.column2CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column2CheckBox.setObjectName("column2CheckBox")
        self.verticalLayout_3.addWidget(self.column2CheckBox)
        self.column3CheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.column3CheckBox.setFont(font)
        self.column3CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column3CheckBox.setObjectName("column3CheckBox")
        self.verticalLayout_3.addWidget(self.column3CheckBox)
        self.column4CheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.column4CheckBox.setFont(font)
        self.column4CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column4CheckBox.setObjectName("column4CheckBox")
        self.verticalLayout_3.addWidget(self.column4CheckBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.column5CheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.column5CheckBox.setFont(font)
        self.column5CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column5CheckBox.setObjectName("column5CheckBox")
        self.verticalLayout_2.addWidget(self.column5CheckBox)
        self.column6CheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.column6CheckBox.setFont(font)
        self.column6CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column6CheckBox.setObjectName("column6CheckBox")
        self.verticalLayout_2.addWidget(self.column6CheckBox)
        self.column7CheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.column7CheckBox.setFont(font)
        self.column7CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column7CheckBox.setObjectName("column7CheckBox")
        self.verticalLayout_2.addWidget(self.column7CheckBox)
        self.column8CheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.column8CheckBox.setFont(font)
        self.column8CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column8CheckBox.setIconSize(QtCore.QSize(16, 16))
        self.column8CheckBox.setObjectName("column8CheckBox")
        self.verticalLayout_2.addWidget(self.column8CheckBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.dispenseVolumeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.dispenseVolumeButton.setObjectName("dispenseVolumeButton")
        self.verticalLayout_4.addWidget(self.dispenseVolumeButton)
        self.dispenseVolumeBox = QtWidgets.QGroupBox(self.dispenseBox)
        self.dispenseVolumeBox.setGeometry(QtCore.QRect(10, 20, 441, 71))
        self.dispenseVolumeBox.setObjectName("dispenseVolumeBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.dispenseVolumeBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 31, 421, 37))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dispenseSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dispenseSpinBox.setFont(font)
        self.dispenseSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dispenseSpinBox.setDecimals(3)
        self.dispenseSpinBox.setMaximum(1000.0)
        self.dispenseSpinBox.setProperty("value", 2.0)
        self.dispenseSpinBox.setObjectName("dispenseSpinBox")
        self.horizontalLayout_4.addWidget(self.dispenseSpinBox)
        self.dispenseUnits = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dispenseUnits.setFont(font)
        self.dispenseUnits.setObjectName("dispenseUnits")
        self.horizontalLayout_4.addWidget(self.dispenseUnits)
        self.dispenseVolumeSlider = QtWidgets.QSlider(self.layoutWidget1)
        self.dispenseVolumeSlider.setEnabled(False)
        self.dispenseVolumeSlider.setMaximum(25)
        self.dispenseVolumeSlider.setProperty("value", 2)
        self.dispenseVolumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dispenseVolumeSlider.setInvertedAppearance(False)
        self.dispenseVolumeSlider.setObjectName("dispenseVolumeSlider")
        self.horizontalLayout_4.addWidget(self.dispenseVolumeSlider)
        self.adjustmentBox = QtWidgets.QGroupBox(self.centralwidget)
        self.adjustmentBox.setGeometry(QtCore.QRect(10, 140, 461, 194))
        self.adjustmentBox.setObjectName("adjustmentBox")
        self.gridLayout = QtWidgets.QGridLayout(self.adjustmentBox)
        self.gridLayout.setObjectName("gridLayout")
        self.emptyLinesButton = QtWidgets.QPushButton(self.adjustmentBox)
        self.emptyLinesButton.setObjectName("emptyLinesButton")
        self.gridLayout.addWidget(self.emptyLinesButton, 2, 1, 1, 1)
        self.primeButton = QtWidgets.QPushButton(self.adjustmentBox)
        self.primeButton.setObjectName("primeButton")
        self.gridLayout.addWidget(self.primeButton, 2, 0, 1, 1)
        self.emptyButton = QtWidgets.QPushButton(self.adjustmentBox)
        self.emptyButton.setObjectName("emptyButton")
        self.gridLayout.addWidget(self.emptyButton, 0, 1, 1, 1)
        self.fillButton = QtWidgets.QPushButton(self.adjustmentBox)
        self.fillButton.setObjectName("fillButton")
        self.gridLayout.addWidget(self.fillButton, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.drawSpeedGroupBox = QtWidgets.QGroupBox(self.adjustmentBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drawSpeedGroupBox.sizePolicy().hasHeightForWidth())
        self.drawSpeedGroupBox.setSizePolicy(sizePolicy)
        self.drawSpeedGroupBox.setObjectName("drawSpeedGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.drawSpeedGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.drawSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.drawSpeedGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.drawSpeedSpinBox.setFont(font)
        self.drawSpeedSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drawSpeedSpinBox.setDecimals(0)
        self.drawSpeedSpinBox.setMaximum(10000.0)
        self.drawSpeedSpinBox.setSingleStep(100.0)
        self.drawSpeedSpinBox.setProperty("value", 0.0)
        self.drawSpeedSpinBox.setObjectName("drawSpeedSpinBox")
        self.horizontalLayout_6.addWidget(self.drawSpeedSpinBox)
        self.drawSpeedUnits = QtWidgets.QLabel(self.drawSpeedGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.drawSpeedUnits.setFont(font)
        self.drawSpeedUnits.setObjectName("drawSpeedUnits")
        self.horizontalLayout_6.addWidget(self.drawSpeedUnits)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.drawSpeedSlider = QtWidgets.QSlider(self.drawSpeedGroupBox)
        self.drawSpeedSlider.setEnabled(False)
        self.drawSpeedSlider.setMaximum(10000)
        self.drawSpeedSlider.setSingleStep(100)
        self.drawSpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.drawSpeedSlider.setObjectName("drawSpeedSlider")
        self.verticalLayout_5.addWidget(self.drawSpeedSlider)
        self.horizontalLayout_5.addWidget(self.drawSpeedGroupBox)
        self.dispenseSpeedGroupBox = QtWidgets.QGroupBox(self.adjustmentBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dispenseSpeedGroupBox.sizePolicy().hasHeightForWidth())
        self.dispenseSpeedGroupBox.setSizePolicy(sizePolicy)
        self.dispenseSpeedGroupBox.setObjectName("dispenseSpeedGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dispenseSpeedGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.dispenseSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.dispenseSpeedGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dispenseSpeedSpinBox.setFont(font)
        self.dispenseSpeedSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dispenseSpeedSpinBox.setDecimals(0)
        self.dispenseSpeedSpinBox.setMaximum(10000.0)
        self.dispenseSpeedSpinBox.setSingleStep(100.0)
        self.dispenseSpeedSpinBox.setProperty("value", 0.0)
        self.dispenseSpeedSpinBox.setObjectName("dispenseSpeedSpinBox")
        self.horizontalLayout_7.addWidget(self.dispenseSpeedSpinBox)
        self.dispenseSpeedUnits = QtWidgets.QLabel(self.dispenseSpeedGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dispenseSpeedUnits.setFont(font)
        self.dispenseSpeedUnits.setObjectName("dispenseSpeedUnits")
        self.horizontalLayout_7.addWidget(self.dispenseSpeedUnits)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.dispenseSpeedSlider = QtWidgets.QSlider(self.dispenseSpeedGroupBox)
        self.dispenseSpeedSlider.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dispenseSpeedSlider.sizePolicy().hasHeightForWidth())
        self.dispenseSpeedSlider.setSizePolicy(sizePolicy)
        self.dispenseSpeedSlider.setMaximum(10000)
        self.dispenseSpeedSlider.setSingleStep(100)
        self.dispenseSpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dispenseSpeedSlider.setObjectName("dispenseSpeedSlider")
        self.verticalLayout.addWidget(self.dispenseSpeedSlider)
        self.horizontalLayout_5.addWidget(self.dispenseSpeedGroupBox)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.refreshButton, self.comPortComboBox)
        MainWindow.setTabOrder(self.comPortComboBox, self.connectButton)
        MainWindow.setTabOrder(self.connectButton, self.syringeComboBox)
        MainWindow.setTabOrder(self.syringeComboBox, self.syringeButton)
        MainWindow.setTabOrder(self.syringeButton, self.initializeButton)
        MainWindow.setTabOrder(self.initializeButton, self.fillButton)
        MainWindow.setTabOrder(self.fillButton, self.emptyButton)
        MainWindow.setTabOrder(self.emptyButton, self.primeButton)
        MainWindow.setTabOrder(self.primeButton, self.emptyLinesButton)
        MainWindow.setTabOrder(self.emptyLinesButton, self.drawSpeedSpinBox)
        MainWindow.setTabOrder(self.drawSpeedSpinBox, self.dispenseSpeedSpinBox)
        MainWindow.setTabOrder(self.dispenseSpeedSpinBox, self.dispenseSpinBox)
        MainWindow.setTabOrder(self.dispenseSpinBox, self.allCheckBox)
        MainWindow.setTabOrder(self.allCheckBox, self.column1CheckBox)
        MainWindow.setTabOrder(self.column1CheckBox, self.column2CheckBox)
        MainWindow.setTabOrder(self.column2CheckBox, self.column3CheckBox)
        MainWindow.setTabOrder(self.column3CheckBox, self.column4CheckBox)
        MainWindow.setTabOrder(self.column4CheckBox, self.column5CheckBox)
        MainWindow.setTabOrder(self.column5CheckBox, self.column6CheckBox)
        MainWindow.setTabOrder(self.column6CheckBox, self.column7CheckBox)
        MainWindow.setTabOrder(self.column7CheckBox, self.column8CheckBox)
        MainWindow.setTabOrder(self.column8CheckBox, self.dispenseVolumeButton)
        MainWindow.setTabOrder(self.dispenseVolumeButton, self.stopButton)
        MainWindow.setTabOrder(self.stopButton, self.dispenseSpeedSlider)
        MainWindow.setTabOrder(self.dispenseSpeedSlider, self.dispenseVolumeSlider)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SEC"))
        self.commsBox.setTitle(_translate("MainWindow", "Communications"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.comPortComboBox.setItemText(0, _translate("MainWindow", "<COM Port>"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.setUpBox.setTitle(_translate("MainWindow", "Set Up"))
        self.syringeComboBox.setItemText(0, _translate("MainWindow", "25 mL"))
        self.syringeComboBox.setItemText(1, _translate("MainWindow", "50 μL"))
        self.syringeComboBox.setItemText(2, _translate("MainWindow", "100 μL"))
        self.syringeComboBox.setItemText(3, _translate("MainWindow", "250 μL"))
        self.syringeComboBox.setItemText(4, _translate("MainWindow", "500 μL"))
        self.syringeComboBox.setItemText(5, _translate("MainWindow", "1 mL"))
        self.syringeComboBox.setItemText(6, _translate("MainWindow", "5 mL"))
        self.syringeComboBox.setItemText(7, _translate("MainWindow", "10 mL"))
        self.syringeButton.setText(_translate("MainWindow", "Set Syringe Size"))
        self.initializeButton.setText(_translate("MainWindow", "Initialize Pump"))
        self.emergencyStopBox.setTitle(_translate("MainWindow", "Emergency Stop"))
        self.stopButton.setText(_translate("MainWindow", "STOP PUMP"))
        self.dispenseBox.setTitle(_translate("MainWindow", "Dispense"))
        self.columnSelectBox.setTitle(_translate("MainWindow", "Column Selection"))
        self.allCheckBox.setText(_translate("MainWindow", "All"))
        self.column1CheckBox.setText(_translate("MainWindow", "Column 1"))
        self.column2CheckBox.setText(_translate("MainWindow", "Column 2"))
        self.column3CheckBox.setText(_translate("MainWindow", "Column 3"))
        self.column4CheckBox.setText(_translate("MainWindow", "Column 4"))
        self.column5CheckBox.setText(_translate("MainWindow", "Column 5"))
        self.column6CheckBox.setText(_translate("MainWindow", "Column 6"))
        self.column7CheckBox.setText(_translate("MainWindow", "Column 7"))
        self.column8CheckBox.setText(_translate("MainWindow", "Column 8"))
        self.dispenseVolumeButton.setText(_translate("MainWindow", "Dispense to Columns"))
        self.dispenseVolumeBox.setTitle(_translate("MainWindow", "Dispense Volume"))
        self.dispenseUnits.setText(_translate("MainWindow", "mL"))
        self.adjustmentBox.setTitle(_translate("MainWindow", "Adjustments"))
        self.emptyLinesButton.setText(_translate("MainWindow", "Empty Lines"))
        self.primeButton.setText(_translate("MainWindow", "Prime/Clean Lines"))
        self.emptyButton.setText(_translate("MainWindow", "Empty Syringe Barrel"))
        self.fillButton.setText(_translate("MainWindow", "Fill Syringe Barrel"))
        self.drawSpeedGroupBox.setTitle(_translate("MainWindow", "Draw Speed"))
        self.drawSpeedUnits.setText(_translate("MainWindow", "steps/s"))
        self.dispenseSpeedGroupBox.setTitle(_translate("MainWindow", "Dispense Speed"))
        self.dispenseSpeedUnits.setText(_translate("MainWindow", "steps/s"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
