# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 800)
        MainWindow.setMinimumSize(QtCore.QSize(480, 800))
        MainWindow.setMaximumSize(QtCore.QSize(480, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Desktop/unnamed.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.commsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.commsBox.setGeometry(QtCore.QRect(10, 0, 461, 71))
        self.commsBox.setObjectName("commsBox")
        self.layoutWidget = QtWidgets.QWidget(self.commsBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 31, 441, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comPortComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comPortComboBox.setObjectName("comPortComboBox")
        self.comPortComboBox.addItem("")
        self.horizontalLayout.addWidget(self.comPortComboBox)
        self.connectButton = QtWidgets.QPushButton(self.layoutWidget)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        self.refreshButton = QtWidgets.QPushButton(self.layoutWidget)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)
        self.setUpBox = QtWidgets.QGroupBox(self.centralwidget)
        self.setUpBox.setGeometry(QtCore.QRect(10, 70, 461, 71))
        self.setUpBox.setObjectName("setUpBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.setUpBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(12, 31, 441, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.syringeComboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.syringeComboBox.setObjectName("syringeComboBox")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.syringeComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.syringeComboBox)
        self.syringeButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.syringeButton.setObjectName("syringeButton")
        self.horizontalLayout_2.addWidget(self.syringeButton)
        self.initializeButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.initializeButton.setObjectName("initializeButton")
        self.horizontalLayout_2.addWidget(self.initializeButton)
        self.emergencyStopBox = QtWidgets.QGroupBox(self.centralwidget)
        self.emergencyStopBox.setGeometry(QtCore.QRect(10, 690, 461, 61))
        self.emergencyStopBox.setObjectName("emergencyStopBox")
        self.stopButton = QtWidgets.QPushButton(self.emergencyStopBox)
        self.stopButton.setGeometry(QtCore.QRect(10, 30, 441, 21))
        self.stopButton.setObjectName("stopButton")
        self.dispenseBox = QtWidgets.QGroupBox(self.centralwidget)
        self.dispenseBox.setGeometry(QtCore.QRect(10, 330, 461, 361))
        self.dispenseBox.setObjectName("dispenseBox")
        self.columnSelectBox = QtWidgets.QGroupBox(self.dispenseBox)
        self.columnSelectBox.setGeometry(QtCore.QRect(10, 90, 441, 261))
        font = QtGui.QFont()
        font.setBold(False)
        self.columnSelectBox.setFont(font)
        self.columnSelectBox.setObjectName("columnSelectBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.columnSelectBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 421, 221))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.allCheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.allCheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.allCheckBox.setFont(font)
        self.allCheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.allCheckBox.setObjectName("allCheckBox")
        self.horizontalLayout_3.addWidget(self.allCheckBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.column1CheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.column1CheckBox.setFont(font)
        self.column1CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column1CheckBox.setObjectName("column1CheckBox")
        self.verticalLayout_3.addWidget(self.column1CheckBox)
        self.column2CheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.column2CheckBox.setFont(font)
        self.column2CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column2CheckBox.setObjectName("column2CheckBox")
        self.verticalLayout_3.addWidget(self.column2CheckBox)
        self.column3CheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.column3CheckBox.setFont(font)
        self.column3CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column3CheckBox.setObjectName("column3CheckBox")
        self.verticalLayout_3.addWidget(self.column3CheckBox)
        self.column4CheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.column4CheckBox.setFont(font)
        self.column4CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column4CheckBox.setObjectName("column4CheckBox")
        self.verticalLayout_3.addWidget(self.column4CheckBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.column5CheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.column5CheckBox.setFont(font)
        self.column5CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column5CheckBox.setObjectName("column5CheckBox")
        self.verticalLayout_2.addWidget(self.column5CheckBox)
        self.column6CheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.column6CheckBox.setFont(font)
        self.column6CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column6CheckBox.setObjectName("column6CheckBox")
        self.verticalLayout_2.addWidget(self.column6CheckBox)
        self.column7CheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.column7CheckBox.setFont(font)
        self.column7CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column7CheckBox.setObjectName("column7CheckBox")
        self.verticalLayout_2.addWidget(self.column7CheckBox)
        self.column8CheckBox = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.column8CheckBox.setFont(font)
        self.column8CheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 40px;\n"
"    height: 40px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"     image: url(./CheckBoxIcons/BlankCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(./CheckBoxIcons/HoverCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     image: url(./CheckBoxIcons/CheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     image: url(./CheckBoxIcons/HoverCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:checked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckedCheckBox400px.svg);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(./CheckBoxIcons/DisabledCheckBox400px.svg);\n"
"}")
        self.column8CheckBox.setIconSize(QtCore.QSize(16, 16))
        self.column8CheckBox.setObjectName("column8CheckBox")
        self.verticalLayout_2.addWidget(self.column8CheckBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.dispenseVolumeButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.dispenseVolumeButton.setObjectName("dispenseVolumeButton")
        self.verticalLayout_4.addWidget(self.dispenseVolumeButton)
        self.dispenseVolumeBox = QtWidgets.QGroupBox(self.dispenseBox)
        self.dispenseVolumeBox.setGeometry(QtCore.QRect(10, 20, 441, 71))
        self.dispenseVolumeBox.setObjectName("dispenseVolumeBox")
        self.layoutWidget3 = QtWidgets.QWidget(self.dispenseVolumeBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 31, 421, 37))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dispenseSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.dispenseSpinBox.setFont(font)
        self.dispenseSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dispenseSpinBox.setDecimals(2)
        self.dispenseSpinBox.setSingleStep(0.1)
        self.dispenseSpinBox.setObjectName("dispenseSpinBox")
        self.horizontalLayout_4.addWidget(self.dispenseSpinBox)
        self.dispenseUnits = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.dispenseUnits.setFont(font)
        self.dispenseUnits.setObjectName("dispenseUnits")
        self.horizontalLayout_4.addWidget(self.dispenseUnits)
        self.volRangeLabel = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volRangeLabel.sizePolicy().hasHeightForWidth())
        self.volRangeLabel.setSizePolicy(sizePolicy)
        self.volRangeLabel.setObjectName("volRangeLabel")
        self.horizontalLayout_4.addWidget(self.volRangeLabel)
        self.adjustmentBox = QtWidgets.QGroupBox(self.centralwidget)
        self.adjustmentBox.setGeometry(QtCore.QRect(10, 140, 461, 191))
        self.adjustmentBox.setObjectName("adjustmentBox")
        self.layoutWidget4 = QtWidgets.QWidget(self.adjustmentBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 90, 441, 101))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.speedGroupBox = QtWidgets.QGroupBox(self.layoutWidget4)
        self.speedGroupBox.setObjectName("speedGroupBox")
        self.layoutWidget5 = QtWidgets.QWidget(self.speedGroupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 35, 201, 61))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.drawSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.drawSpeedSpinBox.setFont(font)
        self.drawSpeedSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.drawSpeedSpinBox.setDecimals(1)
        self.drawSpeedSpinBox.setMinimum(0.1)
        self.drawSpeedSpinBox.setMaximum(3.3)
        self.drawSpeedSpinBox.setSingleStep(0.1)
        self.drawSpeedSpinBox.setObjectName("drawSpeedSpinBox")
        self.horizontalLayout_6.addWidget(self.drawSpeedSpinBox)
        self.drawSpeedUnits = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.drawSpeedUnits.setFont(font)
        self.drawSpeedUnits.setObjectName("drawSpeedUnits")
        self.horizontalLayout_6.addWidget(self.drawSpeedUnits)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addWidget(self.speedGroupBox)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget4)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 33, 201, 61))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.dispenseSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.dispenseSpeedSpinBox.setFont(font)
        self.dispenseSpeedSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dispenseSpeedSpinBox.setDecimals(1)
        self.dispenseSpeedSpinBox.setMinimum(0.1)
        self.dispenseSpeedSpinBox.setMaximum(3.3)
        self.dispenseSpeedSpinBox.setSingleStep(0.1)
        self.dispenseSpeedSpinBox.setObjectName("dispenseSpeedSpinBox")
        self.horizontalLayout_7.addWidget(self.dispenseSpeedSpinBox)
        self.dispenseSpeedUnits = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.dispenseSpeedUnits.setFont(font)
        self.dispenseSpeedUnits.setObjectName("dispenseSpeedUnits")
        self.horizontalLayout_7.addWidget(self.dispenseSpeedUnits)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.layoutWidget7 = QtWidgets.QWidget(self.adjustmentBox)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 30, 441, 56))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.fillButton = QtWidgets.QPushButton(self.layoutWidget7)
        self.fillButton.setObjectName("fillButton")
        self.verticalLayout_7.addWidget(self.fillButton)
        self.primeButton = QtWidgets.QPushButton(self.layoutWidget7)
        self.primeButton.setObjectName("primeButton")
        self.verticalLayout_7.addWidget(self.primeButton)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.emptyButton = QtWidgets.QPushButton(self.layoutWidget7)
        self.emptyButton.setObjectName("emptyButton")
        self.verticalLayout.addWidget(self.emptyButton)
        self.emptyLinesButton = QtWidgets.QPushButton(self.layoutWidget7)
        self.emptyLinesButton.setObjectName("emptyLinesButton")
        self.verticalLayout.addWidget(self.emptyLinesButton)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionConsole = QtWidgets.QAction(MainWindow)
        self.actionConsole.setEnabled(False)
        self.actionConsole.setObjectName("actionConsole")
        self.actionEmergStop = QtWidgets.QAction(MainWindow)
        self.actionEmergStop.setObjectName("actionEmergStop")
        self.actionReconnectInit = QtWidgets.QAction(MainWindow)
        self.actionReconnectInit.setObjectName("actionReconnectInit")
        self.menuFile.addAction(self.actionConsole)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuActions.addAction(self.actionEmergStop)
        self.menuActions.addAction(self.actionReconnectInit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comPortComboBox, self.connectButton)
        MainWindow.setTabOrder(self.connectButton, self.refreshButton)
        MainWindow.setTabOrder(self.refreshButton, self.syringeComboBox)
        MainWindow.setTabOrder(self.syringeComboBox, self.syringeButton)
        MainWindow.setTabOrder(self.syringeButton, self.initializeButton)
        MainWindow.setTabOrder(self.initializeButton, self.fillButton)
        MainWindow.setTabOrder(self.fillButton, self.emptyButton)
        MainWindow.setTabOrder(self.emptyButton, self.primeButton)
        MainWindow.setTabOrder(self.primeButton, self.emptyLinesButton)
        MainWindow.setTabOrder(self.emptyLinesButton, self.drawSpeedSpinBox)
        MainWindow.setTabOrder(self.drawSpeedSpinBox, self.dispenseSpeedSpinBox)
        MainWindow.setTabOrder(self.dispenseSpeedSpinBox, self.dispenseSpinBox)
        MainWindow.setTabOrder(self.dispenseSpinBox, self.allCheckBox)
        MainWindow.setTabOrder(self.allCheckBox, self.column1CheckBox)
        MainWindow.setTabOrder(self.column1CheckBox, self.column2CheckBox)
        MainWindow.setTabOrder(self.column2CheckBox, self.column3CheckBox)
        MainWindow.setTabOrder(self.column3CheckBox, self.column4CheckBox)
        MainWindow.setTabOrder(self.column4CheckBox, self.column5CheckBox)
        MainWindow.setTabOrder(self.column5CheckBox, self.column6CheckBox)
        MainWindow.setTabOrder(self.column6CheckBox, self.column7CheckBox)
        MainWindow.setTabOrder(self.column7CheckBox, self.column8CheckBox)
        MainWindow.setTabOrder(self.column8CheckBox, self.dispenseVolumeButton)
        MainWindow.setTabOrder(self.dispenseVolumeButton, self.stopButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SEC"))
        self.commsBox.setTitle(_translate("MainWindow", "Communications"))
        self.comPortComboBox.setItemText(0, _translate("MainWindow", "<COM Port>"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.refreshButton.setToolTip(_translate("MainWindow", "Refresh the list of COM ports"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.setUpBox.setTitle(_translate("MainWindow", "Set Up"))
        self.syringeComboBox.setItemText(0, _translate("MainWindow", "25 mL"))
        self.syringeComboBox.setItemText(1, _translate("MainWindow", "10 mL"))
        self.syringeComboBox.setItemText(2, _translate("MainWindow", "5 mL"))
        self.syringeComboBox.setItemText(3, _translate("MainWindow", "1 mL"))
        self.syringeComboBox.setItemText(4, _translate("MainWindow", "500 μL"))
        self.syringeComboBox.setItemText(5, _translate("MainWindow", "250 μL"))
        self.syringeComboBox.setItemText(6, _translate("MainWindow", "100 μL"))
        self.syringeComboBox.setItemText(7, _translate("MainWindow", "50 μL"))
        self.syringeButton.setToolTip(_translate("MainWindow", "Set the syringe barrel size (ensure this matches the physical barrel size)"))
        self.syringeButton.setText(_translate("MainWindow", "Set Syringe Size"))
        self.initializeButton.setToolTip(_translate("MainWindow", "Initialize pump before sending commands"))
        self.initializeButton.setText(_translate("MainWindow", "Initialize Pump"))
        self.emergencyStopBox.setTitle(_translate("MainWindow", "Emergency Stop"))
        self.stopButton.setToolTip(_translate("MainWindow", "Interrupt pump and stop all actions."))
        self.stopButton.setText(_translate("MainWindow", "STOP PUMP"))
        self.dispenseBox.setTitle(_translate("MainWindow", "Dispense"))
        self.columnSelectBox.setTitle(_translate("MainWindow", "Column Selection"))
        self.allCheckBox.setText(_translate("MainWindow", "All"))
        self.column1CheckBox.setText(_translate("MainWindow", "Column 1"))
        self.column2CheckBox.setText(_translate("MainWindow", "Column 2"))
        self.column3CheckBox.setText(_translate("MainWindow", "Column 3"))
        self.column4CheckBox.setText(_translate("MainWindow", "Column 4"))
        self.column5CheckBox.setText(_translate("MainWindow", "Column 5"))
        self.column6CheckBox.setText(_translate("MainWindow", "Column 6"))
        self.column7CheckBox.setText(_translate("MainWindow", "Column 7"))
        self.column8CheckBox.setText(_translate("MainWindow", "Column 8"))
        self.dispenseVolumeButton.setToolTip(_translate("MainWindow", "Dispense specified volume from reservoir to column lines*\n"
"* Either all columns, or specified columns"))
        self.dispenseVolumeButton.setText(_translate("MainWindow", "Dispense to Columns"))
        self.dispenseVolumeBox.setTitle(_translate("MainWindow", "Dispense Volume"))
        self.dispenseUnits.setText(_translate("MainWindow", "mL"))
        self.adjustmentBox.setTitle(_translate("MainWindow", "Adjustments"))
        self.speedGroupBox.setTitle(_translate("MainWindow", "Draw Speed"))
        self.drawSpeedUnits.setText(_translate("MainWindow", "mL/s"))
        self.groupBox.setTitle(_translate("MainWindow", "Dispense Speed"))
        self.dispenseSpeedUnits.setText(_translate("MainWindow", "mL/s"))
        self.fillButton.setToolTip(_translate("MainWindow", "Fully draw syringe, from reservoir"))
        self.fillButton.setText(_translate("MainWindow", "Fill Syringe Barrel"))
        self.primeButton.setToolTip(_translate("MainWindow", "1. Draw partly from reservoir.\n"
"2. Dispense back to reservoir (remove any air).\n"
"3. Draw fully from reservoir.\n"
"4. Dispense to each column line equally."))
        self.primeButton.setText(_translate("MainWindow", "Prime/Clean Lines"))
        self.emptyButton.setToolTip(_translate("MainWindow", "Dispense syringe barrel to reservoir"))
        self.emptyButton.setText(_translate("MainWindow", "Empty Syringe Barrel"))
        self.emptyLinesButton.setToolTip(_translate("MainWindow", "Draw from each column line, dispense to reservoir."))
        self.emptyLinesButton.setText(_translate("MainWindow", "Empty Lines"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuActions.setTitle(_translate("MainWindow", "Action"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Quit the application"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionConsole.setText(_translate("MainWindow", "Console"))
        self.actionConsole.setStatusTip(_translate("MainWindow", "Open a console for manual serial commands. Connection must be open."))
        self.actionEmergStop.setText(_translate("MainWindow", "Emergency Stop"))
        self.actionEmergStop.setStatusTip(_translate("MainWindow", "Force stop the pump."))
        self.actionEmergStop.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionReconnectInit.setText(_translate("MainWindow", "Reconnect and Initialize"))
        self.actionReconnectInit.setStatusTip(_translate("MainWindow", "Disconnect, set syringe size, and initialize pump."))
        self.actionReconnectInit.setShortcut(_translate("MainWindow", "Ctrl+R"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
